In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [3]:
import os

data_files = [(x[0], x[2]) for x in os.walk("/content/gdrive/MyDrive/AMLProject/audioNN/WAV_1600")]
#print(data_files)
data_files = data_files[0][1]

In [4]:
fileids = [];
for i in range(len(data_files)):
  fileids.append(data_files[i].strip('.wav'))
print(fileids)

['_BtdwH6mfWg', '_gzYkdjNvPc', '_BvNNdEkhZA', '_HabvL0VnrQ', '_BXmhCPTQmA', '_gr7o5ynhn', '_HanACduNJk', '_iy7ftq27xE', '_iRAn6feOm', '_OmWVs0-6UM', '_K0okiLaF9I', '_KGd7IpX3B4', '_JcML8u5Wes', '_MGd6t9eZP8', '_on_E-ZWy0I', '_PJ26YwqRJE', '_PKP676ez2c', '_qVgNLJCYdA', '_q7DM8WkzAQ', '_v8c7iWkYz0', '_tBaGXNwlp0', '_t8ETpf2LnM', '_UNQDdiAbWI', '_ZlF5Q9W1DM', '_xjBqNfiEY4', '_WA0HtVEe8U', '_XWUKMkxa-Q', '_Vp4SDp_knI', '_YzIvwvyIq4', '_WkXQNVLQXs', '0AA-wmk8WdA', '0AkGtPzl7D8', '0bsTzavb-AE', '0BVed2nBq1g', '0cBmQ_ItVUc', '0bxhZ-LIfZY', '0EAAfLCQabY', '0DBfvvIVmqY', '_1nvuNk7EFY', '0FA32bEZ6xI', '_0efYOjQYRc', '0EphpADwdPg', '0eTibWQdO5M', '_4PNh8dIILI', '_2u0MkRqpjA', '_4K620KW_Is', '_7HVhnSYX1Y', '_26JmJnPKfM', '_BMdEKNF5Js', '_aJghSQmxD8', '_8pvMpMdGM4', '_aZDaIfGfPo', '_bIJOxiIJFk']


In [5]:
import librosa, librosa.display
import matplotlib.pyplot as plt
import numpy as np

signals = []
rates = []
fileids = []
for i in data_files:
    tempdir = '/content/gdrive/MyDrive/AMLProject/audioNN/WAV_1600/' + str(i)
    signal_temp, sampleRate_temp = librosa.load(tempdir, sr=22050)
    fileids.append(i)
    signals.append(signal_temp)
    rates.append(sampleRate_temp)


In [6]:
fileids = [];
for i in range(len(data_files)):
  fileids.append(data_files[i].strip('.wav'))
print(fileids)

['_BtdwH6mfWg', '_gzYkdjNvPc', '_BvNNdEkhZA', '_HabvL0VnrQ', '_BXmhCPTQmA', '_gr7o5ynhn', '_HanACduNJk', '_iy7ftq27xE', '_iRAn6feOm', '_OmWVs0-6UM', '_K0okiLaF9I', '_KGd7IpX3B4', '_JcML8u5Wes', '_MGd6t9eZP8', '_on_E-ZWy0I', '_PJ26YwqRJE', '_PKP676ez2c', '_qVgNLJCYdA', '_q7DM8WkzAQ', '_v8c7iWkYz0', '_tBaGXNwlp0', '_t8ETpf2LnM', '_UNQDdiAbWI', '_ZlF5Q9W1DM', '_xjBqNfiEY4', '_WA0HtVEe8U', '_XWUKMkxa-Q', '_Vp4SDp_knI', '_YzIvwvyIq4', '_WkXQNVLQXs', '0AA-wmk8WdA', '0AkGtPzl7D8', '0bsTzavb-AE', '0BVed2nBq1g', '0cBmQ_ItVUc', '0bxhZ-LIfZY', '0EAAfLCQabY', '0DBfvvIVmqY', '_1nvuNk7EFY', '0FA32bEZ6xI', '_0efYOjQYRc', '0EphpADwdPg', '0eTibWQdO5M', '_4PNh8dIILI', '_2u0MkRqpjA', '_4K620KW_Is', '_7HVhnSYX1Y', '_26JmJnPKfM', '_BMdEKNF5Js', '_aJghSQmxD8', '_8pvMpMdGM4', '_aZDaIfGfPo', '_bIJOxiIJFk']


In [7]:
print([signals[0]])

[array([ 0.000000e+00,  0.000000e+00,  0.000000e+00, ...,  4.306241e-06,
       -7.964126e-07,  0.000000e+00], dtype=float32)]


In [8]:
new_list = signals[0][300:322]
print(new_list)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
a = [1,20,31,4,5,6]
b = a[2:5]
index = a.index(5)
print(index)

4


In [10]:
print(fileids[0])
print(signals[0].shape)
print(signals[2].shape)
print(signals[3].shape)
print(signals[10].shape)

_BtdwH6mfWg
(2189825,)
(2323457,)
(3916289,)
(1169410,)


In [11]:
%cd /content/gdrive/MyDrive/AMLProject/Multimodal_Dataset

/content/gdrive/.shortcut-targets-by-id/19hXWzWoU0l_6KZqYHC_U7mp25fP6na39/AMLProject/Multimodal_Dataset


In [12]:

!git clone https://github.com/A2Zadeh/CMU-MultimodalSDK.git

fatal: destination path 'CMU-MultimodalSDK' already exists and is not an empty directory.


In [13]:
!pip install h5py validators tqdm numpy argparse requests colorama

In [14]:
%set_env PYTHONPATH=/content/gdrive/MyDrive/AMLProject/Multimodal_Dataset/CMU-MultimodalSDK


env: PYTHONPATH=/content/gdrive/MyDrive/AMLProject/Multimodal_Dataset/CMU-MultimodalSDK


In [15]:
import sys
sys.path.insert(1, "/content/gdrive/MyDrive/AMLProject/Multimodal_Dataset/CMU-MultimodalSDK")

In [16]:
import colorama
import mmsdk
from mmsdk import mmdatasdk

In [17]:
import os
from os import listdir
from os.path import isfile, join

# Path to csd files. If path is incorrect or missing the entire dataset will be downloaded
pathf = '/content/gdrive/MyDrive/AMLProject/audioNN/downloaded_datasets'
dataset_dictionary={}


# choice={"cmu_mosei":mmdatasdk.cmu_mosei.highlevel,"cmu_mosi":mmdatasdk.cmu_mosi.highlevel,"pom":mmdatasdk.pom.highlevel}
# labels={"cmu_mosei":mmdatasdk.cmu_mosei.labels,"cmu_mosi":mmdatasdk.cmu_mosi.labels,"pom":mmdatasdk.pom.labels}
##ONLY RUN IF DATASET IS NOT PREVIOUSLY ALIGNED
if os.path.isdir(pathf) is False:
    dataset=mmdatasdk.mmdataset(mmdatasdk.cmu_mosei.highlevel,pathf)
    dataset.add_computational_sequences(mmdatasdk.cmu_mosei.labels,pathf)
else: 
    ##RUN IF DATASET IS PREVIOUSLY ALIGNED aka downloaded previously
    csdfiles = [f for f in listdir(pathf) if isfile(join(pathf, f)) and f[-4:]=='.csd']
    if len(csdfiles)==0:
        print("No csd files in the given folder")
        exit(-2)

    print("%d csd files found"%len(csdfiles))
    for csdfile in csdfiles:
        dataset_dictionary[csdfile]=os.path.join(pathf,csdfile)
    dataset=mmdatasdk.mmdataset(dataset_dictionary)

1 csd files found
[2022-04-23 05:30:10.266] | Success | Computational sequence read from file /content/gdrive/MyDrive/AMLProject/audioNN/downloaded_datasets/CMU_MOSEI_Labels.csd ...
[2022-04-23 05:30:22.111] | Status  | Checking the integrity of the <All Labels> computational sequence ...
[2022-04-23 05:30:22.112] | Status  | Checking the format of the data in <All Labels> computational sequence ...


[2022-04-23 05:30:27.969] | Success | <All Labels> computational sequence data in correct format.
[2022-04-23 05:30:27.969] | Status  | Checking the format of the metadata in <All Labels> computational sequence ...
[2022-04-23 05:30:27.969] | Warning | <All Labels> computational sequence does not have all the required metadata ... continuing 
[2022-04-23 05:30:27.969] | Success | Dataset initialized successfully ... 


In [18]:
print ("List of the computational sequences in the downloaded dataset")
print (dataset.computational_sequences.keys())

List of the computational sequences in the downloaded dataset
dict_keys(['CMU_MOSEI_Labels.csd'])


In [114]:
import pandas as pd
import numpy as np
# The following may require 'CMU_MOSEI_Labels.csd' or 'All Labels' depending on dataset.computational_sequences.keys()
compseq = 'CMU_MOSEI_Labels.csd'

files = []
starts = []
ends = []
sentiment = []
happy = []
sad = []
anger = []
surprise = []
disgust = []
fear = []

for file in dataset.computational_sequences[compseq].keys():
    for index in range(len(dataset.computational_sequences[compseq][file]['intervals'])):
        files += [file]
        starts += [dataset.computational_sequences[compseq][file]['intervals'][index][0]]
        ends += [dataset.computational_sequences[compseq][file]['intervals'][index][1]]
        # sentiment,happy,sad,anger,surprise,disgust,fear
        # dataset.computational_sequences['CMU_MOSEI_Labels.csd']['-3g5yACwYnA']['features'][index][0]
        sentiment += [dataset.computational_sequences[compseq][file]['features'][index][0]]
        happy += [dataset.computational_sequences[compseq][file]['features'][index][1]]
        sad += [dataset.computational_sequences[compseq][file]['features'][index][2]]
        anger += [dataset.computational_sequences[compseq][file]['features'][index][3]]
        surprise += [dataset.computational_sequences[compseq][file]['features'][index][4]]
        disgust += [dataset.computational_sequences[compseq][file]['features'][index][5]]
        fear += [dataset.computational_sequences[compseq][file]['features'][index][6]]
sampled_signal = [None] * len(happy)
df_labels = pd.DataFrame(
    data=np.stack([
        files,
        starts,
        ends,
        sentiment,
        happy,
        sad,
        anger,
        surprise,
        disgust,
        fear,
        sampled_signal
    ], axis=1),
    columns=[
        'file',
        'start',
        'end',
        'sentiment',
        'happy',
        'sad',
        'anger',
        'surprise',
        'disgust',
        'fear',
        'sampled_signal'
    ]
)

In [115]:
print(df_labels)

              file    start      end sentiment     happy       sad anger  \
0      --qXJuDtHPw   23.199   30.325       1.0  0.666667       0.0   0.0   
1      -3g5yACwYnA   82.753  100.555       1.0  0.666667  0.666667   0.0   
2      -3g5yACwYnA  119.919  125.299  0.666667       0.0       0.0   0.0   
3      -3g5yACwYnA     4.84   14.052       0.0  0.666667  0.666667   0.0   
4      -3g5yACwYnA   13.211   27.521       0.0  0.333333  0.333333   0.0   
...            ...      ...      ...       ...       ...       ...   ...   
23254  zwTrXwi54us   47.444   49.312       0.0       0.0       0.0   0.0   
23255  zwTrXwi54us   48.511   53.652       0.0       0.0       0.0   0.0   
23256  zwTrXwi54us   52.652   57.942       1.0       1.0       0.0   0.0   
23257  zwTrXwi54us    57.98   69.326  0.666667  0.333333       0.0   0.0   
23258  zx4W0Vuus-I   15.057   38.327       1.0       1.0       0.0   0.0   

      surprise disgust      fear sampled_signal  
0          0.0     0.0       0.0     

In [116]:
for i in range(len(fileids)):
  
  sampling_rate = 22050
  #target_rows = df_labels.loc[df_labels['file'] == fileids[i]]

  index_array = df_labels[df_labels['file'] == fileids[i]].index.to_numpy()
  print(index_array)

  for index in index_array:
    row = df_labels.iloc[index]
    start_time = int(float(row['start']))
    end_time = int(float(row['end']))
    sample_start_time = start_time * sampling_rate
    sample_end_time = end_time * sampling_rate
    sampled_signals = signals[i][sample_start_time:sample_end_time]
    df_labels.iloc[index].sampled_signal = sampled_signals




[16143 16144]
[16236 16237 16238 16239 16240 16241 16242 16243 16244 16245 16246 16247
 16248 16249 16250 16251 16252 16253]
[16145 16146 16147 16148 16149 16150 16151 16152 16153 16154]
[16155 16156 16157 16158 16159 16160 16161 16162 16163]
[16141 16142]
[]
[16164 16165 16166 16167 16168 16169 16170 16171 16172]
[16259 16260 16261 16262 16263 16264 16265 16266 16267 16268 16269 16270]
[]
[16180 16181 16182 16183]
[16176 16177]
[16178]
[16173 16174 16175]
[16179]
[16271 16272 16273 16274 16275 16276 16277 16278 16279 16280 16281 16282
 16283 16284 16285 16286 16287 16288 16289 16290 16291 16292 16293]
[16184 16185 16186 16187 16188 16189]
[16190 16191 16192 16193 16194 16195 16196 16197]
[16300 16301 16302 16303 16304]
[16294 16295 16296 16297 16298 16299]
[16312 16313 16314 16315 16316 16317]
[16306 16307 16308 16309 16310 16311]
[16305]
[16198 16199 16200 16201]
[16211 16212]
[16318 16319 16320 16321 16322 16323]
[16204]
[16209]
[16202 16203]
[16210]
[16205 16206 16207 16208]
[318 3

In [118]:
print(df_labels.loc[df_labels['file'] == '_BvNNdEkhZA'])

              file   start     end sentiment     happy       sad     anger  \
16145  _BvNNdEkhZA     0.0   6.339       0.0       0.0  0.333333       0.0   
16146  _BvNNdEkhZA  45.298  51.487       0.0       0.0  0.333333       0.0   
16147  _BvNNdEkhZA  56.154  67.121      -1.0       0.0  0.666667       0.0   
16148  _BvNNdEkhZA   66.49  70.613 -0.666667       0.0       0.0       0.0   
16149  _BvNNdEkhZA  70.002  85.878       0.0  0.333333  0.666667       0.0   
16150  _BvNNdEkhZA  85.268  88.672  0.666667  0.666667       0.0       0.0   
16151  _BvNNdEkhZA  94.117  102.86  0.666667  0.333333       0.0       0.0   
16152  _BvNNdEkhZA  17.921  24.009       0.0       0.0       0.0  0.333333   
16153  _BvNNdEkhZA  23.558  28.808       1.0  0.333333       0.0       0.0   
16154  _BvNNdEkhZA  29.664  33.727  0.333333       0.0       0.0       0.0   

       surprise   disgust      fear  \
16145       0.0       0.0       0.0   
16146       0.0       0.0       0.0   
16147  0.333333       0.

In [ ]:
MFCCs = []
numSamplesFFT = 2048
hopLength = 512

for i in range(len(fileids)):
  index_array = df_labels[df_labels['file'] == fileids[i]].index.to_numpy()

  for index in index_array:
    current_signal = df_labels.iloc[index].sampled_signal
    if(len(current_signal)!=0):
      MFCC = librosa.feature.mfcc(current_signal, n_fft=numSamplesFFT, hop_length=hopLength, n_mfcc=13)
      MFCCs.append(MFCC)
      librosa.display.specshow(MFCC, sr=rates[i], hop_length=hopLength)
      plt.savefig('/content/gdrive/MyDrive/AMLProject/audioNN/MFCCs/' + str(fileids[i]) + '_sample_' + str(index))