In [6]:
import pandas as pd
import numpy as np

filename = 'Labels/5000_batch_raw.csv'
df = pd.read_csv(filename)

In [15]:
df.describe()

MaxAssignments  AssignmentDurationInSeconds  \
count         15000.0                      15000.0   
mean              3.0                        900.0   
std               0.0                          0.0   
min               3.0                        900.0   
25%               3.0                        900.0   
50%               3.0                        900.0   
75%               3.0                        900.0   
max               3.0                        900.0   

       AutoApprovalDelayInSeconds  NumberOfSimilarHITs  LifetimeInSeconds  \
count                     15000.0                  0.0                0.0   
mean                     259200.0                  NaN                NaN   
std                           0.0                  NaN                NaN   
min                      259200.0                  NaN                NaN   
25%                      259200.0                  NaN                NaN   
50%                      259200.0                  NaN                NaN   
75%                      259200.0                  NaN                NaN   
max                      259200.0                  NaN                NaN   

       ApprovalTime  RejectionTime  RequesterFeedback  WorkTimeInSeconds  \
count           0.0            0.0                0.0       15000.000000   
mean            NaN            NaN                NaN          77.049067   
std             NaN            NaN                NaN         115.300142   
min             NaN            NaN                NaN           3.000000   
25%             NaN            NaN                NaN          22.000000   
50%             NaN            NaN                NaN          35.000000   
75%             NaN            NaN                NaN          74.000000   
max             NaN            NaN                NaN         896.000000   

         Input.CLIP  ...  Answer.disgust   Answer.fear  Answer.gender  \
count  15000.000000  ...    14951.000000  14953.000000        14952.0   
mean       7.778800  ...        0.046084      0.093694            0.0   
std        7.034911  ...        0.253041      0.388241            0.0   
min        0.000000  ...        0.000000      0.000000            0.0   
25%        2.000000  ...        0.000000      0.000000            0.0   
50%        6.000000  ...        0.000000      0.000000            0.0   
75%       11.000000  ...        0.000000      0.000000            0.0   
max       48.000000  ...        3.000000      3.000000            0.0   

       Answer.happiness  Answer.sadness  Answer.sentiment  Answer.surprise  \
count      14953.000000    14952.000000      14957.000000     14947.000000   
mean           0.514211        0.181915          0.486060         0.046096   
std            0.813100        0.542932          1.197482         0.253866   
min            0.000000        0.000000         -3.000000         0.000000   
25%            0.000000        0.000000          0.000000         0.000000   
50%            0.000000        0.000000          0.000000         0.000000   
75%            1.000000        0.000000          1.000000         0.000000   
max            3.000000        3.000000          3.000000         3.000000   

       Answer.video_load  Approve  Reject  
count       14997.000000      0.0     0.0  
mean            0.033740      NaN     NaN  
std             0.180565      NaN     NaN  
min             0.000000      NaN     NaN  
25%             0.000000      NaN     NaN  
50%             0.000000      NaN     NaN  
75%             0.000000      NaN     NaN  
max             1.000000      NaN     NaN  

[8 rows x 21 columns]

In [4]:
import os

data_files = [(x[0], x[2]) for x in os.walk("AudioFiles")]
data_files = data_files[0][1]

fileids = [];
for i in range(len(data_files)):
    fileids.append(data_files[i].strip('.wav'))
print(fileids)

['_4PNh8dIILI', '_bIJOxiIJFk', '_aJghSQmxD8', '0bsTzavb-AE', '_q7DM8WkzAQ', '0bxhZ-LIfZY', '_XWUKMkxa-Q', '_gzYkdjNvPc', '_PKP676ez2c', '_0efYOjQYRc', '_26JmJnPKfM', '_2u0MkRqpjA', '_v8c7iWkYz0', '_t8ETpf2LnM', '_OmWVs0-6UM', '_MGd6t9eZP8', '0eTibWQdO5M', '_Vp4SDp_knI', '0EphpADwdPg', '_8pvMpMdGM4', '_JcML8u5Wes', '_on_E-ZWy0I', '_xjBqNfiEY4', '_K0okiLaF9I', '_BMdEKNF5Js', '_aZDaIfGfPo', '_KGd7IpX3B4', '_BtdwH6mfWg', '_WkXQNVLQXs', '_ZlF5Q9W1DM', '_iy7ftq27xE', '0FA32bEZ6xI', '_tBaGXNwlp0', '_HabvL0VnrQ', '0cBmQ_ItVUc', '_gr7o5ynhn', '_BXmhCPTQmA', '0EAAfLCQabY', '0DBfvvIVmqY', '0BVed2nBq1g', '_iRAn6feOm', '_UNQDdiAbWI', '_4K620KW_Is', '_WA0HtVEe8U', '_qVgNLJCYdA', '_HanACduNJk', '_YzIvwvyIq4', '0AA-wmk8WdA', '_PJ26YwqRJE', '0AkGtPzl7D8', '_1nvuNk7EFY', '_7HVhnSYX1Y', '_BvNNdEkhZA']


In [9]:
df.loc[df['Input.VIDEO_ID'] == '_tBaGXNwlp0'].shape

(12, 43)

In [33]:
curr = df.loc[df['Input.VIDEO_ID'] == '_tBaGXNwlp0']
temp = curr['Answer.sadness'].head(1)
print(int(temp))

1


In [138]:
from matplotlib.image import imread
X = []
y = []
for i in fileids:
    Mfcc = imread('MFCCs/' + str(i) + '.png')
    curr = df.loc[df['Input.VIDEO_ID'] == str(i)]
    if not curr['Answer.anger'].head(1).empty: 
        temp = []
        temp.append(int(curr['Answer.anger'].head(1)))
        temp.append(int(curr['Answer.disgust'].head(1)))
        temp.append(int(curr['Answer.fear'].head(1)))
        temp.append(int(curr['Answer.happiness'].head(1)))
        temp.append(int(curr['Answer.sadness'].head(1)))
        temp.append(int(curr['Answer.surprise'].head(1)))
        temp.append(int(curr['Answer.sentiment'].head(1)))
        
        print(len(Mfcc))
        print(len(Mfcc[0]))
        print(Mfcc[0][0])
        print(np.array(Mfcc).shape)
        X.append(np.array(Mfcc))
        y.append(np.array(temp))

288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 432, 4)
288
432
[1. 1. 1. 0.]
(288, 

In [120]:
print(len(X))
print(len(y))

30
30


In [115]:
for i in range(10):
    print(X[i])

[[[1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  ...
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]]

 [[1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  ...
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]]

 [[1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  ...
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]]

 ...

 [[1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  ...
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]]

 [[1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  ...
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]]

 [[1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  ...
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]]]
[[[1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  ...
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]]

 [[1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  ...
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]]

 [[1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  ...
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]]

 ...

 [[1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  ..

In [150]:
X = np.array(X)
y = np.array(y)

In [151]:
print(X.shape)
print(y.shape)

(30, 288, 432, 4)
(30, 7)


In [152]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)
X.shape

(30, 288, 432, 4)

In [167]:
from numpy import mean
from numpy import std
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import RepeatedKFold
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Dense, Dropout, Flatten
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
 
# get the model
def get_model():
    model = Sequential()
    model.add(Conv2D(filters=16, kernel_size=(5, 5), activation="relu", input_shape=(288, 432, 4)))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.25))
    model.add(Conv2D(filters=32, kernel_size=(5, 5), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.25))
    model.add(Conv2D(filters=64, kernel_size=(5, 5), activation="relu"))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.25))
    model.add(Conv2D(filters=64, kernel_size=(5, 5), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.25))
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(64, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(7, activation='sigmoid'))
    return model
 
# evaluate a model using repeated k-fold cross-validation

results = list()
Filelength = int(len(X) * 0.8)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)
    
model = get_model()
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test), batch_size=64)
yhat = model.predict(X_test)




Epoch 1/10
1/1 [==============================] - 5s 5s/step - loss: 0.8028 - accuracy: 0.1667 - val_loss: 0.5469 - val_accuracy: 0.3333
Epoch 2/10
1/1 [==============================] - 3s 3s/step - loss: 1.2337 - accuracy: 0.2083 - val_loss: 0.6361 - val_accuracy: 0.3333
Epoch 3/10
1/1 [==============================] - 3s 3s/step - loss: 0.8879 - accuracy: 0.1667 - val_loss: 0.6769 - val_accuracy: 0.3333
Epoch 4/10
1/1 [==============================] - 3s 3s/step - loss: 0.6008 - accuracy: 0.1667 - val_loss: 0.6815 - val_accuracy: 0.3333
Epoch 5/10
1/1 [==============================] - 3s 3s/step - loss: 0.6001 - accuracy: 0.3333 - val_loss: 0.6736 - val_accuracy: 0.3333
Epoch 6/10
1/1 [==============================] - 3s 3s/step - loss: 0.6112 - accuracy: 0.2083 - val_loss: 0.6605 - val_accuracy: 0.3333
Epoch 7/10
1/1 [==============================] - 3s 3s/step - loss: 0.5292 - accuracy: 0.2083 - val_loss: 0.6385 - val_accuracy: 0.3333
Epoch 8/10
1/1 [=========================

In [165]:
print(yhat)
yhat = yhat.round()
print(yhat)
print(y_test)

[[0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]
[[0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]
[[ 1  0  0  0  0  1 -1]
 [ 0  0  0  1  0  0  1]
 [ 0  0  0  0  0  0  0]
 [ 0  0  1  0  1  0 -1]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0]]


In [166]:
total = 0
similar = 0
for i in range(len(y_test)):
    for j in range(len(y_test[i])):
        if y_test[i][j] == yhat[i][j]:
            similar += 1
        total += 1
acc = similar/total

print('>%.3f' % acc)
results.append(acc)

>0.714
